/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hangman;
import java.util.Random;
import java.time.LocalDateTime;  
import java.time.format.DateTimeFormatter;
import javax.swing.Timer;
import java.awt.event.*;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author Gian
 */
public class Game extends javax.swing.JFrame {
    /**
     * Creates new form startGame
     */
    public Game() {
        initComponents();
        head.setVisible(false);
        rightArm.setVisible(false);
        rightLeg.setVisible(false);
        body.setVisible(false);
        leftLeg.setVisible(false);
        leftArm.setVisible(false);
        popLose.setVisible(false);
        popWin.setVisible(false);
        popSkip.setVisible(false);
        wrong.setVisible(false);
        initial();
        getPanels();
        curDateTime();
        dateAndTime.setVisible(true);
        this.score = 100;
        backScores.setToolTipText("Click this button to return to the menu.");
        jButton1.setToolTipText("Click this button to skip to the next game.");
        
                KeyStroke exitKey = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false);
        Action exitAction = new AbstractAction(){
            public void actionPerformed(ActionEvent e){
                System.exit(0);
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(exitKey, "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", exitAction);
        
        KeyStroke creditsKey = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0, false);
        Action creditsAction = new AbstractAction(){
            public void actionPerformed(ActionEvent e){
                dispose();
                new Credits().setVisible(true);
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(creditsKey, "F1");
        getRootPane().getActionMap().put("F1", creditsAction);
    }
    
    public int getscores(){
        return this.score;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backScores = new javax.swing.JButton();
        z = new javax.swing.JButton();
        x = new javax.swing.JButton();
        c = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        v = new javax.swing.JButton();
        b = new javax.swing.JButton();
        m = new javax.swing.JButton();
        n = new javax.swing.JButton();
        a = new javax.swing.JButton();
        s = new javax.swing.JButton();
        d = new javax.swing.JButton();
        h = new javax.swing.JButton();
        g = new javax.swing.JButton();
        j = new javax.swing.JButton();
        k = new javax.swing.JButton();
        l = new javax.swing.JButton();
        q = new javax.swing.JButton();
        w = new javax.swing.JButton();
        e = new javax.swing.JButton();
        f = new javax.swing.JButton();
        r = new javax.swing.JButton();
        t = new javax.swing.JButton();
        y = new javax.swing.JButton();
        u = new javax.swing.JButton();
        i = new javax.swing.JButton();
        o = new javax.swing.JButton();
        p = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dateAndTime = new javax.swing.JLabel();
        popSkip = new javax.swing.JLayeredPane();
        jLabel15 = new javax.swing.JLabel();
        gameOverBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        popLose = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        noChoice = new javax.swing.JButton();
        yesChoice = new javax.swing.JButton();
        popWin = new javax.swing.JLayeredPane();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        noChoice1 = new javax.swing.JButton();
        yesChoice1 = new javax.swing.JButton();
        head = new javax.swing.JLabel();
        body = new javax.swing.JLabel();
        rightLeg = new javax.swing.JLabel();
        rightArm = new javax.swing.JLabel();
        leftArm = new javax.swing.JLabel();
        leftLeg = new javax.swing.JLabel();
        wrong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Start Game");
        setResizable(false);
        getContentPane().setLayout(null);

        backScores.setBackground(new java.awt.Color(153, 153, 153));
        backScores.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        backScores.setForeground(new java.awt.Color(255, 255, 255));
        backScores.setText("Back");
        backScores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backScoresActionPerformed(evt);
            }
        });
        getContentPane().add(backScores);
        backScores.setBounds(10, 340, 72, 26);

        z.setText("Z");
        z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zActionPerformed(evt);
            }
        });
        getContentPane().add(z);
        z.setBounds(110, 320, 50, 50);

        x.setText("X");
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });
        getContentPane().add(x);
        x.setBounds(170, 320, 50, 50);

        c.setText("C");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        getContentPane().add(c);
        c.setBounds(230, 320, 50, 50);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 120)); // NOI18N
        jLabel3.setText("Γ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 20, 70, 89);

        v.setText("V");
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });
        getContentPane().add(v);
        v.setBounds(290, 320, 50, 50);

        b.setText("B");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(350, 320, 50, 50);

        m.setText("M");
        m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mActionPerformed(evt);
            }
        });
        getContentPane().add(m);
        m.setBounds(470, 320, 50, 50);

        n.setText("N");
        n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nActionPerformed(evt);
            }
        });
        getContentPane().add(n);
        n.setBounds(410, 320, 50, 50);

        a.setText("A");
        a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aActionPerformed(evt);
            }
        });
        getContentPane().add(a);
        a.setBounds(40, 260, 50, 50);

        s.setText("S");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        getContentPane().add(s);
        s.setBounds(100, 260, 50, 50);

        d.setText("D");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(160, 260, 50, 50);

        h.setText("H");
        h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hActionPerformed(evt);
            }
        });
        getContentPane().add(h);
        h.setBounds(340, 260, 50, 50);

        g.setText("G");
        g.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gActionPerformed(evt);
            }
        });
        getContentPane().add(g);
        g.setBounds(280, 260, 50, 50);

        j.setText("J");
        j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActionPerformed(evt);
            }
        });
        getContentPane().add(j);
        j.setBounds(400, 260, 50, 50);

        k.setText("K");
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });
        getContentPane().add(k);
        k.setBounds(460, 260, 50, 50);

        l.setText("L");
        l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lActionPerformed(evt);
            }
        });
        getContentPane().add(l);
        l.setBounds(520, 260, 50, 50);

        q.setText("Q");
        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });
        getContentPane().add(q);
        q.setBounds(10, 200, 50, 50);

        w.setText("W");
        w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wActionPerformed(evt);
            }
        });
        getContentPane().add(w);
        w.setBounds(70, 200, 50, 50);

        e.setText("E");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(130, 200, 50, 50);

        f.setText("F");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(220, 260, 50, 50);

        r.setText("R");
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });
        getContentPane().add(r);
        r.setBounds(190, 200, 50, 50);

        t.setText("T");
        t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tActionPerformed(evt);
            }
        });
        getContentPane().add(t);
        t.setBounds(250, 200, 50, 50);

        y.setText("Y");
        y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yActionPerformed(evt);
            }
        });
        getContentPane().add(y);
        y.setBounds(310, 200, 50, 50);

        u.setText("U");
        u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uActionPerformed(evt);
            }
        });
        getContentPane().add(u);
        u.setBounds(370, 200, 50, 50);

        i.setText("I");
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        getContentPane().add(i);
        i.setBounds(430, 200, 50, 50);

        o.setText("O");
        o.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oActionPerformed(evt);
            }
        });
        getContentPane().add(o);
        o.setBounds(490, 200, 50, 50);

        p.setText("P");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        getContentPane().add(p);
        p.setBounds(550, 200, 50, 50);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("_");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 140, 50, 50);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("_");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 140, 50, 50);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("_");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 140, 50, 50);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("_");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(190, 140, 50, 50);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("_");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 140, 50, 50);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("_");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 140, 50, 50);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("_");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(370, 140, 50, 50);

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("_");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 140, 50, 50);

        jButton1.setText("Skip");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(520, 40, 78, 23);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Score");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(520, 10, 80, 16);

        dateAndTime.setText("dateAndTime");
        getContentPane().add(dateAndTime);
        dateAndTime.setBounds(330, 0, 170, 30);

        popSkip.setBackground(new java.awt.Color(153, 153, 153));
        popSkip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        popSkip.setOpaque(true);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Game Over!");
        popSkip.add(jLabel15);
        jLabel15.setBounds(20, 20, 160, 50);

        gameOverBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gameOverBtn.setText("Continue");
        gameOverBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gameOverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameOverBtnActionPerformed(evt);
            }
        });
        popSkip.add(gameOverBtn);
        gameOverBtn.setBounds(60, 90, 62, 21);

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Score: 0");
        popSkip.add(jLabel16);
        jLabel16.setBounds(60, 60, 60, 16);

        getContentPane().add(popSkip);
        popSkip.setBounds(0, 0, 180, 140);

        popLose.setBackground(new java.awt.Color(153, 153, 153));
        popLose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        popLose.setMaximumSize(new java.awt.Dimension(180, 140));
        popLose.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("You Lost!");
        popLose.add(jLabel13);
        jLabel13.setBounds(40, 20, 140, 50);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Try Again?");
        popLose.add(jLabel14);
        jLabel14.setBounds(60, 60, 70, 17);

        noChoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        noChoice.setText("No");
        noChoice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        noChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noChoiceActionPerformed(evt);
            }
        });
        popLose.add(noChoice);
        noChoice.setBounds(110, 90, 60, 21);

        yesChoice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        yesChoice.setText("Yes");
        yesChoice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yesChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesChoiceActionPerformed(evt);
            }
        });
        popLose.add(yesChoice);
        yesChoice.setBounds(20, 90, 60, 21);

        getContentPane().add(popLose);
        popLose.setBounds(0, 0, 180, 140);

        popWin.setBackground(new java.awt.Color(153, 153, 153));
        popWin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        popWin.setOpaque(true);

        jLabel17.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("You Won!");
        popWin.add(jLabel17);
        jLabel17.setBounds(40, 20, 130, 50);

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Try Again?");
        popWin.add(jLabel18);
        jLabel18.setBounds(60, 60, 70, 17);

        noChoice1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        noChoice1.setText("No");
        noChoice1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        noChoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noChoice1ActionPerformed(evt);
            }
        });
        popWin.add(noChoice1);
        noChoice1.setBounds(110, 90, 60, 21);

        yesChoice1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        yesChoice1.setText("Yes");
        yesChoice1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yesChoice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesChoice1ActionPerformed(evt);
            }
        });
        popWin.add(yesChoice1);
        yesChoice1.setBounds(20, 90, 60, 21);

        getContentPane().add(popWin);
        popWin.setBounds(0, 0, 180, 140);

        head.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        head.setText("O");
        getContentPane().add(head);
        head.setBounds(300, 40, 20, 20);

        body.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        body.setText("  |");
        getContentPane().add(body);
        body.setBounds(290, 50, 40, 40);

        rightLeg.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rightLeg.setText("\\");
            getContentPane().add(rightLeg);
            rightLeg.setBounds(310, 90, 30, 20);

            rightArm.setText("____\\");
                getContentPane().add(rightArm);
                rightArm.setBounds(310, 50, 40, 20);

                leftArm.setText("/____");
                getContentPane().add(leftArm);
                leftArm.setBounds(280, 50, 40, 20);

                leftLeg.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
                leftLeg.setText("  /");
                getContentPane().add(leftLeg);
                leftLeg.setBounds(280, 90, 30, 20);

                wrong.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
                wrong.setForeground(new java.awt.Color(153, 51, 0));
                wrong.setText("You got it wrong!");
                getContentPane().add(wrong);
                wrong.setBounds(370, 80, 100, 20);

                setSize(new java.awt.Dimension(616, 408));
                setLocationRelativeTo(null);
            }// </editor-fold>//GEN-END:initComponents

    private void backScoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backScoresActionPerformed
        dispose();
        new Menu().setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_backScoresActionPerformed

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
        letter = 'q';
        printPanel();
        q.setVisible(false);
    }//GEN-LAST:event_qActionPerformed

    private void wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wActionPerformed
        letter = 'w';
        printPanel();
        w.setVisible(false);
    }//GEN-LAST:event_wActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        letter = 'e';
        printPanel();
        e.setVisible(false);
    }//GEN-LAST:event_eActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
        letter = 'r';
        printPanel();
        r.setVisible(false);
    }//GEN-LAST:event_rActionPerformed

    private void tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tActionPerformed
        letter = 't';
        printPanel();
        t.setVisible(false);
    }//GEN-LAST:event_tActionPerformed

    private void yActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yActionPerformed
        letter = 'y';
        printPanel();
        y.setVisible(false);
    }//GEN-LAST:event_yActionPerformed

    private void uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uActionPerformed
        letter = 'u';
        printPanel();
        u.setVisible(false);
    }//GEN-LAST:event_uActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        letter = 'i';
        printPanel();
        i.setVisible(false);
    }//GEN-LAST:event_iActionPerformed

    private void oActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oActionPerformed
        letter = 'o';
        printPanel();
        o.setVisible(false);
    }//GEN-LAST:event_oActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        letter = 'p';
        printPanel();
        p.setVisible(false);
    }//GEN-LAST:event_pActionPerformed

    private void aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aActionPerformed
        letter = 'a';
        printPanel();
        a.setVisible(false);
    }//GEN-LAST:event_aActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        letter = 's';
        printPanel();
        s.setVisible(false);
    }//GEN-LAST:event_sActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        letter = 'd';
        printPanel();
        d.setVisible(false);
    }//GEN-LAST:event_dActionPerformed

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        letter = 'f';
        printPanel();
        f.setVisible(false);
    }//GEN-LAST:event_fActionPerformed

    private void gActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gActionPerformed
        letter = 'g';
        printPanel();
        g.setVisible(false);
    }//GEN-LAST:event_gActionPerformed

    private void hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hActionPerformed
        letter = 'h';
        printPanel();
        h.setVisible(false);
    }//GEN-LAST:event_hActionPerformed

    private void jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActionPerformed
        letter = 'j';
        printPanel();
        j.setVisible(false);
    }//GEN-LAST:event_jActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        letter = 'k';
        printPanel();
        k.setVisible(false);
    }//GEN-LAST:event_kActionPerformed

    private void lActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lActionPerformed
        letter = 'l';
        printPanel();
        l.setVisible(false);
    }//GEN-LAST:event_lActionPerformed

    private void zActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zActionPerformed
        letter = 'z';
        printPanel();
        z.setVisible(false);
    }//GEN-LAST:event_zActionPerformed

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        letter = 'x';
        printPanel();
        x.setVisible(false);
    }//GEN-LAST:event_xActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        letter = 'c';
        printPanel();
        c.setVisible(false);
    }//GEN-LAST:event_cActionPerformed

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        letter = 'v';
        printPanel();
        v.setVisible(false);
    }//GEN-LAST:event_vActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        letter = 'b';
        printPanel();
        b.setVisible(false);
    }//GEN-LAST:event_bActionPerformed

    private void nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nActionPerformed
        letter = 'n';
        printPanel();
        n.setVisible(false);
    }//GEN-LAST:event_nActionPerformed

    private void mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mActionPerformed
        letter = 'm';
        printPanel();
        m.setVisible(false);
    }//GEN-LAST:event_mActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    score = 0;
    popSkip.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void yesChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesChoiceActionPerformed
        dispose();
        new Game().setVisible(true);
    }//GEN-LAST:event_yesChoiceActionPerformed

    private void noChoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noChoiceActionPerformed
        dispose();
        new ColorGame(getscores()).setVisible(true);
    }//GEN-LAST:event_noChoiceActionPerformed

    private void gameOverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameOverBtnActionPerformed
        dispose();
        new ColorGame(getscores()).setVisible(true);
    }//GEN-LAST:event_gameOverBtnActionPerformed

    private void noChoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noChoice1ActionPerformed
        dispose();
        new ColorGame(getscores()).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_noChoice1ActionPerformed

    private void yesChoice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesChoice1ActionPerformed
       dispose();
       new Game().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_yesChoice1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private char letter;
    private String word = "";
    private final static String wordBank[] = {"nurse", "climbing", "cemetary", "pharmacy", "abstract"};
    private static int letters = 0;
    private int [] numbers;
    private int mistakes = 0;
    private int correct = 0;
    private int score;
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
                
            }
        });
    }
    
    
    
    public void curDateTime()
    {
        int delay = 0; //milliseconds
        ActionListener taskPerformer = new ActionListener() {
          public void actionPerformed(ActionEvent evt) {
              String date = new java.text.SimpleDateFormat("MM/dd/yyyy HH:mm:ss").format(new java.util.Date(System.currentTimeMillis()));
              dateAndTime.setText(date);
          }
      };
      new Timer(delay, taskPerformer).start();
        
    }
    
    public String getRandomWord()
    {
        Random random = new Random();
        int rand = random.nextInt(4);
        word = wordBank[rand];
        return word;
    }
    public int[] getNumber(){
        int [] numbers = new int [3];
        letters = 0;
        int x = 0;
        char[] Word = new char[word.length()];
        for (int i = 0; i<word.length(); i++){
            Word[i] = word.charAt(i);
        }
        for (int i = 0; i<word.length(); i++){
            if(Word[i] == letter){
                letters = i + 1;
                if(letters!= 0){
                    numbers[x] = letters;
                    x++;
                }
            }
        }
        if (letters == 0){
            mistakes++;
            score = score - 10;
            wrong.setVisible(true);
        }
        jLabel2.setText("Score : " + String.valueOf(score));
        return numbers;
    }
    
    public void scoreTest(){
        ;
    }
    
    private void CheckMistakes(){
    if (mistakes == 1)
        head.setVisible(true);
    else if (mistakes == 2)
        body.setVisible(true);
    else if (mistakes == 3)
        leftArm.setVisible(true);
    else if(mistakes == 4)
        rightArm.setVisible(true);
    else if(mistakes == 5)
        leftLeg.setVisible(true);
    else if(mistakes == 6){
        rightLeg.setVisible(true);
        popLose.setVisible(true);
    }
}
   public void initial(){
            score = 100;
            jLabel4.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            jLabel2.setText("Score : " + String.valueOf(score));
   }
    public void getPanels(){
        String word = getRandomWord();
        int stringLength = word.length();
        if(stringLength == 5 ){
            jLabel6.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
            jLabel11.setVisible(true);
                    }
        else if(stringLength == 8) {
            jLabel4.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jLabel9.setVisible(true);
            jLabel10.setVisible(true);
            jLabel11.setVisible(true);
            jLabel12.setVisible(true);
        }
    }
    public void printPanel(){
        String newLetter = "" +letter;
        int stringLength = word.length();
        numbers = getNumber();
        int size = numbers.length;
        if(stringLength == 5 ){
            for( int i = 0; i<size; i++) {
                letters = numbers[i];
            if (letters == 1){
            jLabel6.setVisible(false);   
            jLabel6.setText(newLetter);
            jLabel6.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
        
            if (letters == 2){
            jLabel8.setVisible(false);   
            jLabel8.setText(newLetter);
            jLabel8.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            if (letters == 3){
            jLabel9.setVisible(false);   
            jLabel9.setText(newLetter);
            jLabel9.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            if (letters == 4){
            jLabel10.setVisible(false);   
            jLabel10.setText(newLetter);
            jLabel10.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            if (letters == 5){
            jLabel11.setVisible(false);   
            jLabel11.setText(newLetter);
            jLabel11.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            
        }
        }
        else{
            for( int i = 0; i<size; i++) {
                letters = numbers[i];
            if (letters == 1){
            jLabel7.setVisible(false);   
            jLabel7.setText(newLetter);
            jLabel7.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
        
            if (letters == 2){
            jLabel6.setVisible(false);   
            jLabel6.setText(newLetter);
            jLabel6.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            if (letters == 3){
            jLabel8.setVisible(false);   
            jLabel8.setText(newLetter);
            jLabel8.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            if (letters == 4){
            jLabel9.setVisible(false);   
            jLabel9.setText(newLetter);
            jLabel9.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            if (letters == 5){
            jLabel10.setVisible(false);   
            jLabel10.setText(newLetter);
            jLabel10.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            if (letters == 6){
            jLabel11.setVisible(false);   
            jLabel11.setText(newLetter);
            jLabel11.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            if (letters == 7){
            jLabel12.setVisible(false);   
            jLabel12.setText(newLetter);
            jLabel12.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            if (letters == 8){
            jLabel4.setVisible(false);   
            jLabel4.setText(newLetter);
            jLabel4.setVisible(true);
            correct++;
            wrong.setVisible(false);
            }
            }
        }
        CheckMistakes();
        Correct();
    }
    public void Correct(){
        int stringLength = word.length();
        if(stringLength ==5){
            if(correct == 5){
                popWin.setVisible(true);
            }
        }
        else{
            if(correct == 8){
                popWin.setVisible(true);
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton b;
    private javax.swing.JButton backScores;
    private javax.swing.JLabel body;
    private javax.swing.JButton c;
    private javax.swing.JButton d;
    private javax.swing.JLabel dateAndTime;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton g;
    private javax.swing.JButton gameOverBtn;
    private javax.swing.JButton h;
    private javax.swing.JLabel head;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JLabel leftArm;
    private javax.swing.JLabel leftLeg;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton noChoice;
    private javax.swing.JButton noChoice1;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JLayeredPane popLose;
    private javax.swing.JLayeredPane popSkip;
    private javax.swing.JLayeredPane popWin;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JLabel rightArm;
    private javax.swing.JLabel rightLeg;
    private javax.swing.JButton s;
    private javax.swing.JButton t;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JButton w;
    private javax.swing.JLabel wrong;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton yesChoice;
    private javax.swing.JButton yesChoice1;
    private javax.swing.JButton z;
    // End of variables declaration//GEN-END:variables
}
